// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type PageRoutes = never
type LayoutRoutes = never
type RedirectRoutes = "/login" | "/settings/sessions"
type RewriteRoutes = "/api/accounting/[[...path]]" | "/api/agents" | "/api/agents/" | "/api/agents/[[...path]]" | "/api/ai/[[...path]]" | "/api/analytics/[[...path]]" | "/api/atom-agent/[[...path]]" | "/api/atom/[[...path]]" | "/api/auth/change-password" | "/api/auth/forgot-password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/profile" | "/api/auth/refresh" | "/api/auth/register" | "/api/auth/reset-password" | "/api/auth/verify-token" | "/api/chat/[[...path]]" | "/api/documents" | "/api/documents/[[...path]]" | "/api/financial/[[...path]]" | "/api/health/[[...path]]" | "/api/integrations/[[...path]]" | "/api/intelligence/[[...path]]" | "/api/sales/[[...path]]" | "/api/system/[[...path]]" | "/api/time-travel/[[...path]]" | "/api/v1/[[...path]]" | "/api/v1/employee/[[...path]]" | "/api/workflow-agent/[[...path]]" | "/api/workflow-templates/[[...path]]" | "/api/workflows/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/api/accounting/[[...path]]": { "path"?: string[]; }
  "/api/agents": {}
  "/api/agents/": {}
  "/api/agents/[[...path]]": { "path"?: string[]; }
  "/api/ai/[[...path]]": { "path"?: string[]; }
  "/api/analytics/[[...path]]": { "path"?: string[]; }
  "/api/atom-agent/[[...path]]": { "path"?: string[]; }
  "/api/atom/[[...path]]": { "path"?: string[]; }
  "/api/auth/change-password": {}
  "/api/auth/forgot-password": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/profile": {}
  "/api/auth/refresh": {}
  "/api/auth/register": {}
  "/api/auth/reset-password": {}
  "/api/auth/verify-token": {}
  "/api/chat/[[...path]]": { "path"?: string[]; }
  "/api/documents": {}
  "/api/documents/[[...path]]": { "path"?: string[]; }
  "/api/financial/[[...path]]": { "path"?: string[]; }
  "/api/health/[[...path]]": { "path"?: string[]; }
  "/api/integrations/[[...path]]": { "path"?: string[]; }
  "/api/intelligence/[[...path]]": { "path"?: string[]; }
  "/api/sales/[[...path]]": { "path"?: string[]; }
  "/api/system/[[...path]]": { "path"?: string[]; }
  "/api/time-travel/[[...path]]": { "path"?: string[]; }
  "/api/v1/[[...path]]": { "path"?: string[]; }
  "/api/v1/employee/[[...path]]": { "path"?: string[]; }
  "/api/workflow-agent/[[...path]]": { "path"?: string[]; }
  "/api/workflow-templates/[[...path]]": { "path"?: string[]; }
  "/api/workflows/[[...path]]": { "path"?: string[]; }
  "/login": {}
  "/settings/sessions": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
